# Generated by Django 2.0.1 on 2018-01-25 03:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=40, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pro_status', models.IntegerField(default=1)),
                ('pro_type', models.IntegerField()),
                ('pro_num', models.IntegerField()),
                ('pro_volume', models.IntegerField()),
                ('pro_introduction', models.CharField(max_length=255)),
                ('shop_id', models.IntegerField()),
                ('img_1', models.URLField()),
                ('img_2', models.URLField()),
                ('img_3', models.URLField()),
                ('isdelete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product',
            },
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
