# Generated by Django 2.0.1 on 2018-02-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showgoods', '0001_initial'),
        ('shopcart', '0002_auto_20180126_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drder_item',
            new_name='Order_item',
        ),
    ]
